// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkyRfG-e_hLfBBBgs41GI-yQUvGMN_NnU',
    appId: '1:887368194549:web:250edf408914b6a9cce8bc',
    messagingSenderId: '887368194549',
    projectId: 'manga-box-a06e0',
    authDomain: 'manga-box-a06e0.firebaseapp.com',
    storageBucket: 'manga-box-a06e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoEUGLuA5rqRJWhG3SFJP_od_Clguply0',
    appId: '1:887368194549:android:af74f1cdb0a1bf5fcce8bc',
    messagingSenderId: '887368194549',
    projectId: 'manga-box-a06e0',
    storageBucket: 'manga-box-a06e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA78bLVhovD6JqIQHBrpZ2sWz12eRID5eM',
    appId: '1:887368194549:ios:1c15cefe955b93a7cce8bc',
    messagingSenderId: '887368194549',
    projectId: 'manga-box-a06e0',
    storageBucket: 'manga-box-a06e0.appspot.com',
    iosClientId:
        '887368194549-qv1s41k7cl9lkvh3imfbirfmbn9kt85p.apps.googleusercontent.com',
    iosBundleId: 'com.example.mangabox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA78bLVhovD6JqIQHBrpZ2sWz12eRID5eM',
    appId: '1:887368194549:ios:1c15cefe955b93a7cce8bc',
    messagingSenderId: '887368194549',
    projectId: 'manga-box-a06e0',
    storageBucket: 'manga-box-a06e0.appspot.com',
    iosClientId:
        '887368194549-qv1s41k7cl9lkvh3imfbirfmbn9kt85p.apps.googleusercontent.com',
    iosBundleId: 'com.example.mangabox',
  );
}
